`define CODE_ADDR_WIDTH  10
`define CODE_ADDR_TOP  9
`define CODE_SIZE_MAX_WORDS  1024
`define NUM_REGS  32
`define TOP_REG  31
`define NUM_GP  8
`define TOP_GP  7
`define IO  8
`define SR_G6  6
`define DR_G6  6
`define SR_G7  7
`define DR_G7  7
`define SR_RSTK  8
`define DR_RSTK  8
`define SR_EVENT_PRIORITY  9
`define DR_EVENT_PRIORITY  9
`define SR_SOFT_EVENT  10
`define DR_SOFT_EVENT  10
`define EVENT_CONTROLLER_RESET_BIT  15
`define EVENT_CONTROLLER_RESET_MASK  32768
`define SR_USAGE_COUNT  11
`define DR_USAGE_COUNT  11
`define SR_USTIMER0  12
`define DR_USTIMER0  12
`define SR_MSTIMER0  13
`define DR_MSTIMER0  13
`define SR_MSTIMER1  14
`define DR_MSTIMER1  14
`define SR_SPI_DATA  15
`define DR_SPI_DATA  15
`define SR_AV_WRITE_DATA  16
`define DR_AV_WRITE_DATA  16
`define SR_AV_READ_DATA  17
`define SR_AV_AD_HI  18
`define DR_AV_AD_HI  18
`define SR_AV_AD_LO  19
`define DR_AV_AD_LO  19
`define SDRAM_BASE  0
`define SDRAM_BASE_HI  0
`define SDRAM_BASE_LO  0
`define SDRAM_SIZE  33554432
`define SDRAM_SIZE_HI  512
`define SDRAM_SIZE_LO  0
`define SR_FDUART_DATA  20
`define DR_FDUART_DATA  20
`define SR_FDUART_STATUS  21
`define DR_FDUART_STATUS  21
`define SR_LEDS  22
`define DR_LEDS  22
`define SR_BOARD_CTRL  23
`define DR_BOARD_CTRL  23
`define DIPSWITCH0_BIT  0
`define DIPSWITCH1_BIT  1
`define DIPSWITCH2_BIT  2
`define DIPSWITCH3_BIT  3
`define KEY0_BIT  4
`define KEY1_BIT  5
`define BEEPER_ENABLE_BIT  6
`define FTDI_POWER_BIT  7
`define SR_ANMUX_CTRL  24
`define DR_ANMUX_CTRL  24
`define ANMUX_ENABLE_MASK  8
`define ANMUX_CHANNEL_MASK  7
`define SR_POWER_DUTY  25
`define DR_POWER_DUTY  25
`define SR_EFI_LEN_US  26
`define DR_EFI_LEN_US  26
`define SR_IGN_TIMEOUT_LEN_20US  27
`define DR_IGN_TIMEOUT_LEN_20US  27
`define SR_IGN_CAPTURE_JF  28
`define DR_IGN_CAPTURE_JF  28
`define ATX_FIFO_EMPTY_BIT  0
`define ATX_FIFO_FULL_BIT  1
`define ATX_BUSY_BIT  2
`define ARX_FIFO_EMPTY_BIT  3
`define ARX_FIFO_FULL_BIT  4
`define ARX_BUSY_BIT  5
`define ATX_FIFO_EMPTY_MASK  1
`define ATX_FIFO_FULL_MASK  2
`define ATX_BUSY_MASK  4
`define ARX_FIFO_EMPTY_MASK  8
`define ARX_FIFO_FULL_MASK  16
`define ARX_BUSY_MASK  32
