`define WORD_WIDTH  16
`define WW  16
`define WORD_MSB  15
`define WMSB  15
`define DEST_LSB  10
`define DEST_WIDTH  6
`define DEST_MAX  63
`define SRC_MSB  9
`define SRC_WIDTH  10
`define SRC_MAX  1023
`define IPR_WIDTH  16
`define IPR_TOP  15
`define DEST_NOP  50
`define DEBUG_IN_WIDTH  19
`define DEBUG_FORCE_EXEC_BIT  18
`define DEBUG_FORCE_LOAD_EXR_BIT  17
`define DEBUG_FORCE_HOLD_STATE_BIT  16
`define DEBUG_OUT_WIDTH  7
`define DEBUG_PRG_BREAK_OP_BIT  6
`define DEBUG_BRANCHING_CYCLE_BIT  5
`define DEBUG_CONST16_CYCLE1_BIT  4
`define DEBUG_FETCH_CYCLE1_BIT  3
`define DEBUG_FETCH_CYCLE2_BIT  2
`define DEBUG_LOAD_EXR_BIT  1
`define DEBUG_ENABLE_EXEC_BIT  0
`define MIN_POPULATED_EXT_REGS  2
`define MAX_POPULATED_EXT_REGS  48
`define SR_A  0
`define DR_A  0
`define SR_B  1
`define DR_B  1
`define SR_I  2
`define DR_I  2
`define SR_J  3
`define DR_J  3
`define SR_X  4
`define DR_X  4
`define SR_Y  5
`define DR_Y  5
`define SR_A+B  768
`define SR_I+J  784
`define SR_X+Y  800
`define SR_AND  816
`define SR_OR  820
`define SR_XOR  824
`define SR_A>>1  848
`define SR_A<<1  849
`define SR_A<<4  850
`define SR_A>>4  851
`define SR_0XFFFF  864
`define CODE_ADDR_WIDTH  12
`define CODE_ADDR_TOP  11
`define CODE_SIZE_MAX_WORDS  4096
`define NUM_POPULATED_EXT_REGS  48
`define TOP_POPULATED_EXT_REG  47
`define NUM_GP  18
`define TOP_GP  17
`define SR_GA  6
`define DR_GA  6
`define SR_GB  7
`define DR_GB  7
`define SR_GC  8
`define DR_GC  8
`define SR_GD  9
`define DR_GD  9
`define SR_GE  10
`define DR_GE  10
`define SR_GF  11
`define DR_GF  11
`define SR_SCROLL_DIR  12
`define DR_SCROLL_DIR  12
`define SR_PUFFING  13
`define DR_PUFFING  13
`define SR_PA  14
`define DR_PA  14
`define SR_PB  15
`define DR_PB  15
`define SR_PC  16
`define DR_PC  16
`define SR_PD  17
`define DR_PD  17
`define SR_RSTK  18
`define DR_RSTK  18
`define SR_EVENT_PRIORITY  19
`define DR_EVENT_PRIORITY  19
`define SR_SOFT_EVENT  20
`define DR_SOFT_EVENT  20
`define EVENT_CONTROLLER_RESET_BIT  15
`define EVENT_CONTROLLER_RESET_MASK  32768
`define SR_TIMESTAMP_LO  21
`define DR_TIMESTAMP_LO  21
`define SR_TIMESTAMP_HI  22
`define DR_TIMESTAMP_HI  22
`define SR_TIMESTAMP_COMPARE_LO  23
`define DR_TIMESTAMP_COMPARE_LO  23
`define SR_TIMESTAMP_COMPARE_HI  24
`define DR_TIMESTAMP_COMPARE_HI  24
`define SR_USTIMER0  25
`define DR_USTIMER0  25
`define SR_MSTIMER0  26
`define DR_MSTIMER0  26
`define SR_POWER_DUTY  27
`define DR_POWER_DUTY  27
`define SR_IGN_PERIOD  28
`define DR_IGN_PERIOD  28
`define SR_IGN_CYCLE_CNT  29
`define DR_IGN_CYCLE_CNT  29
`define SR_PUFF1CNT  30
`define DR_PUFF1CNT  30
`define SR_PUFF1LEN  31
`define ADC_NUM_CHANNELS  8
`define ANMUX_ADC_CHANNEL  7
`define SR_ADC_MAF  32
`define DR_ADC_MAF  32
`define SR_ADC_O2  33
`define DR_ADC_O2  33
`define SR_ADC_TPS  34
`define DR_ADC_TPS  34
`define ANMUX_NUM_CHANNELS  8
`define SR_ANMUX_READ  35
`define SR_ANMUX_BLOCK_TEMP  36
`define DR_ANMUX_BLOCK_TEMP  36
`define SR_ANMUX_TRANS_TEMP  37
`define DR_ANMUX_TRANS_TEMP  37
`define SR_FDUART_DATA  38
`define DR_FDUART_DATA  38
`define SR_FDUART_STATUS  39
`define DR_FDUART_STATUS  39
`define SR_LEDS  40
`define DR_LEDS  40
`define ATX_FIFO_EMPTY_BIT  0
`define ATX_FIFO_FULL_BIT  1
`define ATX_BUSY_BIT  2
`define ARX_FIFO_EMPTY_BIT  3
`define ARX_FIFO_FULL_BIT  4
`define ARX_BUSY_BIT  5
`define ATX_FIFO_EMPTY_MASK  1
`define ATX_FIFO_FULL_MASK  2
`define ATX_BUSY_MASK  4
`define ARX_FIFO_EMPTY_MASK  8
`define ARX_FIFO_FULL_MASK  16
`define ARX_BUSY_MASK  32
