`define MIN_NUM_REGS  2
`define MAX_NUM_REGS  48
`define WORD_WIDTH  16
`define WW  16
`define WORD_MSB  15
`define WMSB  15
`define DEST_LSB  10
`define DEST_WIDTH  6
`define SRC_MSB  9
`define SRC_WIDTH  10
`define IPR_WIDTH  16
`define IPR_TOP  15
`define DEST_NOP  50
`define DEBUG_IN_WIDTH  19
`define DEBUG_FORCE_EXEC_BIT  18
`define DEBUG_FORCE_LOAD_EXR_BIT  17
`define DEBUG_FORCE_HOLD_STATE_BIT  16
`define DEBUG_OUT_WIDTH  8
`define DEBUG_CRITICAL_SECTION_BIT  7
`define DEBUG_PRG_BREAK_OP_BIT  6
`define DEBUG_BRANCHING_CYCLE_BIT  5
`define DEBUG_CONST16_CYCLE1_BIT  4
`define DEBUG_FETCH_CYCLE1_BIT  3
`define DEBUG_FETCH_CYCLE2_BIT  2
`define DEBUG_LOAD_EXR_BIT  1
`define DEBUG_ENABLE_EXEC_BIT  0
`define CODE_ADDR_WIDTH  12
`define CODE_ADDR_TOP  11
`define CODE_SIZE_MAX_WORDS  4096
`define NUM_REGS  17
`define TOP_REG  16
`define NUM_GP  12
`define TOP_GP  11
`define SR_G6  6
`define DR_G6  6
`define SR_G7  7
`define DR_G7  7
`define SR_GA  6
`define DR_GA  6
`define SR_GB  7
`define DR_GB  7
`define SR_PA  8
`define DR_PA  8
`define SR_PB  9
`define DR_PB  9
`define SR_PC  10
`define DR_PC  10
`define SR_PD  11
`define DR_PD  11
`define SR_RSTK  12
`define DR_RSTK  12
`define SR_FDUART_DATA  13
`define DR_FDUART_DATA  13
`define SR_FDUART_STATUS  14
`define DR_FDUART_STATUS  14
`define SR_EXP  15
`define DR_EXP  15
`define SR_EXP_ADDR  16
`define DR_EXP_ADDR  16
`define EXP_NUM_REGS  6
`define EXP_TOP_REG  5
`define ATX_FIFO_EMPTY_BIT  0
`define ATX_FIFO_FULL_BIT  1
`define ATX_BUSY_BIT  2
`define ARX_FIFO_EMPTY_BIT  3
`define ARX_FIFO_FULL_BIT  4
`define ARX_BUSY_BIT  5
`define ATX_FIFO_EMPTY_MASK  1
`define ATX_FIFO_FULL_MASK  2
`define ATX_BUSY_MASK  4
`define ARX_FIFO_EMPTY_MASK  8
`define ARX_FIFO_FULL_MASK  16
`define ARX_BUSY_MASK  32
