`define NUM_REGS  32
`define TOP_REG  31
`define NUM_GP  8
`define TOP_GP  7
`define IO  8
`define NUM_REGS  32
`define TOP_REG  31
`define NUM_GP  8
`define TOP_GP  7
`define IO  8
`define VISOR_NUM_REGS  25
`define VISOR_TOP_REG  24
`define VISOR_NUM_GP  8
`define VISOR_TOP_GP  7
`define VIO  8
`define VISOR_NUM_REGS  25
`define VISOR_TOP_REG  24
`define VISOR_NUM_GP  8
`define VISOR_TOP_GP  7
`define VIO  8
