`define NUM_REGS  32
`define TOP_REG  31
`define NUM_GP  8
`define TOP_GP  7
`define IO  8
`define SR_G6  6
`define DR_G6  6
`define SR_G7  7
`define DR_G7  7
`define SR_RSTK  8
`define DR_RSTK  8
`define SR_LEDS  9
`define DR_LEDS  9
`define SR_ATX_DATA  10
`define DR_ATX_DATA  10
`define SR_ATX_CTRL  11
`define DR_ATX_CTRL  11
`define ATX_LOAD_MASK  1
`define ATX_BUSY_MASK  2
`define ARX_BUSY_MASK  4
`define SR_AV_WRITEDATA  12
`define DR_AV_WRITEDATA  12
`define SR_AV_ADDRESS  13
`define DR_AV_ADDRESS  13
`define JTAG_UART_BASE  256
`define JTAG_UART_DATA  256
`define JTAG_UART_CTRL  257
`define SR_KEYS  14
