`define NUM_REGS  32
`define TOP_REG  31
`define NUM_GP  8
`define TOP_GP  7
`define IO  8
`define SR_G6  6
`define DR_G6  6
`define SR_G7  7
`define DR_G7  7
`define SR_KEYS  8
`define SR_LEDS  9
`define DR_LEDS  9
`define SR_RSTK  10
`define DR_RSTK  10
`define SR_ANMUX_CTRL  11
`define DR_ANMUX_CTRL  11
`define ANMUX_ENABLE_MASK  8
`define SR_DE0NANO_ADC_CTRL  12
`define DR_DE0NANO_ADC_CTRL  12
`define DE0NANO_ADC_CSN_MASK  4
`define DE0NANO_ADC_SCK_MASK  2
`define DE0NANO_ADC_MO_MASK  1
`define DE0NANO_ADC_MI_MASK  1
`define SR_AV_WRITE_DATA  13
`define DR_AV_WRITE_DATA  13
`define SR_AV_READ_DATA  14
`define SR_AV_AD_HI  15
`define DR_AV_AD_HI  15
`define SR_AV_AD_LO  16
`define DR_AV_AD_LO  16
`define SDRAM_BASE  0
`define SDRAM_BASE_HI  0
`define SDRAM_BASE_LO  0
`define SDRAM_SIZE  33554432
`define SDRAM_SIZE_HI  512
`define SDRAM_SIZE_LO  0
`define SR_ATX_DATA  17
`define DR_ATX_DATA  17
`define SR_ATX_CTRL  18
`define DR_ATX_CTRL  18
`define ATX_LOAD_MASK  1
`define ATX_BUSY_MASK  2
`define ARX_BUSY_MASK  4
