`define NUM_REGS  32
`define TOP_REG  31
`define NUM_GP  8
`define TOP_GP  7
`define IO  8
`define SR_G6  6
`define DR_G6  6
`define SR_G7  7
`define DR_G7  7
`define SR_RSTK  8
`define DR_RSTK  8
`define SR_LEDS  9
`define DR_LEDS  9
`define SR_AV_DATA  10
`define DR_AV_DATA  10
`define SR_AV_AD_HI  11
`define DR_AV_AD_HI  11
`define SR_AV_AD_LO  12
`define DR_AV_AD_LO  12
`define SDRAM_BASE  0
`define SDRAM_BASE_HI  0
`define SDRAM_BASE_LO  0
`define SDRAM_SIZE  33554432
`define SDRAM_SIZE_HI  512
`define SDRAM_SIZE_LO  0
`define JTAG_UART_BASE  33554432
`define JTAG_UART_BASE_HI  512
`define JTAG_UART_BASE_LO  0
`define JTAG_UART_DATA  33554432
`define JTAG_UART_DATA_HI  512
`define JTAG_UART_DATA_LO  0
`define JTAG_UART_CTRL  33554433
`define JTAG_UART_CTRL_HI  512
`define JTAG_UART_CTRL_LO  1
`define SR_KEYS  13
