`define VISOR_NUM_REGS  25
`define VISOR_TOP_REG  24
`define VISOR_NUM_GP  8
`define VISOR_TOP_GP  7
`define VIO  8
`define SR_G6  6
`define DR_G6  6
`define SR_G7  7
`define DR_G7  7
`define SR_BP0_ADDR  8
`define DR_BP0_ADDR  8
`define SR_BP1_ADDR  9
`define DR_BP1_ADDR  9
`define SR_BP2_ADDR  10
`define DR_BP2_ADDR  10
`define SR_BP3_ADDR  11
`define DR_BP3_ADDR  11
`define BP_DISABLE  65535
`define SR_FORCE_OPCODE  12
`define DR_FORCE_OPCODE  12
`define SR_POKE_DATA  13
`define DR_POKE_DATA  13
`define SR_AV_WRITEDATA  14
`define DR_AV_WRITEDATA  14
`define SR_AV_ADDRESS  15
`define DR_AV_ADDRESS  15
`define JTAG_UART_BASE  256
`define JTAG_UART_DATA  256
`define JTAG_UART_CTRL  257
`define SR_BUS_CTRL  16
`define DR_BUS_CTRL  16
`define DIVERT_CODE_BUS_MASK  4
`define TG_RESET_MASK  2
`define TG_CODE_READY_MASK  1
`define SR_TG_FORCE  17
`define DR_TG_FORCE  17
`define TG_DEBUG_FORCE_EXEC_MASK  4
`define TG_DEBUG_FORCE_LOAD_EXR_MASK  2
`define TG_DEBUG_HOLD_MASK  1
`define SR_AV_CTRL  18
`define DR_AV_CTRL  18
`define AV_WRITE_MASK  1
`define SR_EXR_SHADOW  19
`define SR_TG_CODE_ADDR  20
`define SR_PEEK_DATA  21
`define SR_TG_DEBUG_OUT  22
`define SR_BP_STATUS  23
`define SR_AV_WAITREQUEST  24
`define DR_DEBUG_PEEK_REG  31
